config/routes.rb
HowWasYourDay::Application.routes.draw do
	match 'rate/:id' => 'rating#rate'

	resource :user do
		resources :statuses do
			get 'calendar', :on => :collection
		end
	end
	get "home/public"
	get "home/index"
	get "home/about"

  root :to => "home#index"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
	before_filter :authorize
	# GET /statuses
	# GET /statuses.xml
	def index
		@user = current_user
		if @user
			earliest = @user.statuses.minimum("for_date")
			days_since_start = (Time.now.to_date - earliest).to_i + 1
			if days_since_start > 28
				@num_days = 28
			else
				@num_days = days_since_start
			end
			@user_statuses = @user.statuses
			@date_range = []
			(1..@num_days).each do |days_back|
				date_to_look_at = days_back.days.ago.to_date
				found_match = false
				@user_statuses.each do |user_status|
					if user_status.for_date == date_to_look_at
						@date_range.push [days_back.days.ago.to_date, user_status]
						found_match = true
					end
				end
				@date_range.push([days_back.days.ago.to_date, "blank"]) unless found_match
			end
		end

		respond_to do |format|
			format.html # index.html.erb
			format.xml	{ render :xml => @user_statuses }
		end
	end

	def calendar
		@user = current_user
		@user_statuses = @user.statuses

		respond_to do |format|
			format.html # index.html.erb
			format.xml	{ render :xml => @user_statuses }
		end
	end

	# GET /statuses/1
	# GET /statuses/1.xml
	def show
		@user = User.find current_user.id
		@user_status = Status.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.xml	{ render :xml => @user_status }
		end
	end

	# GET /statuses/new
	# GET /statuses/new.xml
	def new
		@user = User.find current_user.id
		@user_status = Status.new :user => @user
		if params[:date]
			@user_status.for_date = params[:date]
		end

		respond_to do |format|
			format.html # new.html.erb
			format.xml	{ render :xml => @status }
		end
	end

	# GET /statuses/1/edit
	def edit
		@user = User.find current_user.id
		@user_status = Status.find(params[:id])
	end

	# POST /statuses
	# POST /statuses.xml
	def create
		@user = current_user
		params[:status][:user_id] = @user.id
		@user_status = Status.new(params[:status])

		respond_to do |format|
			if @user_status.save
				format.html { redirect_to(home_index_path, :notice => 'Status was successfully created.') }
				format.xml	{ render :xml => @user_status, :status => :created, :location => @user_status }
			else
				format.html { render :action => "new" }
				format.xml	{ render :xml => @user_status.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /statuses/1
	# PUT /statuses/1.xml
	def update
		@user = current_user
		params[:status][:user_id] = @user.id
		@user_status = Status.find(params[:id])

		respond_to do |format|
			if @user_status.update_attributes(params[:status])
				format.html { redirect_to(home_index_path, :notice => 'Status was successfully updated.') }
				format.xml	{ head :ok }
			else
				format.html { render :action => "edit" }
				format.xml	{ render :xml => @user_status.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /statuses/1
	# DELETE /statuses/1.xml
	def destroy
		@user_status = Status.find(params[:id])
		if @user_status.user == current_user
			@user_status.destroy
		end

		respond_to do |format|
			format.html { redirect_to(home_index_path) }
			format.xml	{ head :ok }
		end
	end
end

app/helpers/statuses_helper.rb
module StatusesHelper
	def status_display(status)
		
	end
end

app/views/statuses/_form.html.erb
<%= form_for(@user_status, :url => user_statuses_path) do |f| %>
  <% if @user_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @user_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<% if params[:date].nil? %>
  <div class="field">
    <%= f.label :for_date %><br />
    <%= f.date_select :for_date %>
  </div>
	<% else %>
	<h2><%= date_format @user_status.for_date %></h2>
	<%= f.hidden_field :for_date %>
	<% end %>
  <div class="field">
		<%= f.hidden_field :rating %>
		<ul id="rating-picklist">
		<li id="good" class="rating smileys-smiley_good_unselected"><%= link_to_function "Good", "hyd.set_status('good', #{current_user.id}, '#{@user_status.for_date}')" %></li>
		<li id="mixed" class="rating smileys-smiley_mixed_unselected"><%= link_to_function "Mixed", "hyd.set_status('mixed', #{current_user.id}, '#{@user_status.for_date}')" %></li>
		<li id="bad" class="rating smileys-smiley_bad_unselected"><%= link_to_function "Bad", "hyd.set_status('bad', #{current_user.id}, '#{@user_status.for_date}')" %></li>
		</ul>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/_status_listing.html.erb
<div id="statuses">
	<% @date_range.each do |date_rating| %>
		<% if date_rating.last == "blank" %>
			<a href="<%= new_user_status_path %>?date=<%= date_rating.first %>">
		<div class="rating smileys-smiley_<%= date_rating.last.downcase %>" title=""><span class="rating-name"><%= date_rating.last %></span></div>
		<% if @date_range.first == date_rating %>
		<div id="starting-date"><%= @date_range.first.first.strftime('%A') %></div>
		<% end %>
		<% if @date_range.last == date_rating %>
		<div id="ending-date"><%= @date_range.last.first.strftime('%A') %><br/>
			<%= @date_range.last.first.strftime('%B %d') %></div>
		<% end %>
		</a>
		<% else %>
			<a href="<%= user_status_path(date_rating.last) %>">
<div class="rating smileys-smiley_<%= date_rating.last.rating.downcase %>" title="<%= date_rating.last.display_status %>"><span class="rating-name"><%= date_rating.last.rating %></span></div>
<% if @date_range.first == date_rating %>
<div id="starting-date"><%= @date_range.first.first.strftime('%A') %></div>
<% end %>
<% if @date_range.last == date_rating %>
<div id="ending-date"><%= @date_range.last.first.strftime('%A') %><br/>
	<%= @date_range.last.first.strftime('%B %d') %></div>
<% end %>
</a>
		<% end %>
	<% end %>
</div>

app/views/statuses/calendar.html.erb
<%= calendar_for(@user_statuses, :html => {:class => "calendar"}) do |status| %>
	<%= status.head('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun') %>
	<%= status.day do |day, statuses| %>
		<%= day.day %>
		<% if statuses.empty?  && day > Time.now.to_date %>
		&nbsp;
		<% elsif statuses.empty?  && day < Time.now.to_date %>
			<div class="calendar-rating smileys-smiley_blank">&nbsp;</div>
		<% else %>
			<% statuses.each do |stat| %>
				<div class="calendar-rating smileys-smiley_<%= stat.rating.downcase %>">&nbsp;</div>
			<% end %>
		<% end %>
	<% end %>
<% end %>

<%= link_to 'New Status', new_user_status_path %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', user_statuses_path %>

app/views/statuses/index.html.erb
<h2>Last <%= @num_days%> Days</h2>
<%= render "status_listing" %>
<div>
<%= link_to 'Calendar', calendar_user_statuses_path %>
<%= link_to 'New Status', new_user_status_path %>
</div>

app/views/statuses/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', user_statuses_path %>

app/views/statuses/show.html.erb
<div id="statuses">
	<h2><%= date_format @user_status.for_date %></h2>
	<div class="rating smileys-smiley_<%= @user_status.rating.downcase %>" title="<%= @user_status.display_status %>">
		&nbsp;
	</div>
	<br/>
	<h3><%= @user_status.comments %></h3>
</div>
<%= link_to 'Delete', user_status_path(current_user, @user_status), :method => :delete %><br/>
<%= link_to 'Back', user_statuses_path %>