config/routes.rb
HowWasYourDay::Application.routes.draw do
	match 'rate/:id' => 'rating#rate'

	resource :user do
		resources :statuses do
			get 'calendar', :on => :collection
		end
	end
	get "home/public"
	get "home/index"
	get "home/about"

  root :to => "home#index"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_login_form.html.erb
<div id="login-form" style="display:none;">
	<%= form_for :session, :url => session_path do |form| %>
		<div class="text_field">
			<%= form.label :email %>
			<%= form.text_field :email%>
		</div>
		<div class="text_field">
			<%= form.label :password %>
			<%= form.password_field :password %>
		</div>
		<div class="submit_field">
			<%= form.submit "Sign in", :disable_with => "Please wait..." %>
		</div>
	<% end %>
	<ul>
		<li>
			<%= link_to "Forgot password?", new_password_path %>
		</li>
	</ul>
</div>

app/views/layouts/_messages.html.erb
<% if flash && !flash.empty? && (flash.values.to_s.strip != "" || flash.values.to_s.strip != "[]") %>
<%= link_to_function "X", "hyd.close_announcements()", :id => "announcements-close", :title => "Close this announcement" %>
	<% [:error, :warning, :info, :notice].each do |type| %>
		<% if flash[type] %>
			<%= content_tag(:p, raw(flash[type]), :id => "flash-message", :class => type.to_s) %>
		<% end %>
	<% end %>
<% end %>

app/views/layouts/_user_info.html.erb
<p>Logged in as <%= link_to current_user.email, edit_user_url, :title => "Edit your preferences" %><br/>
	<span class="small"><%= link_to "Sign Out", sign_out_path, :method => :DELETE %></span></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>How Was Your Day? | <%= @page_title %></title>
	<%= stylesheet_link_tag 'iphone.css', :media => 'only screen and (max-width: 480px)' %>
	<%= stylesheet_link_tag 'screen.css', :media => 'screen and (min-width: 481px)' %>
	<%= stylesheet_link_tag 'print.css', :media => 'print' %>
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
	<meta name="viewport" content="width=device-width" />
</head>
<body class="bp">
	<div id="container" class="container">
		<div id="header">
			<div id="masthead">
				<h1><%= link_to "How was your day?", "/" %></h1>
				<p>Keep track of your daily state of mind.</p>
			</div>
			<div id="login-section">
				<% if signed_in? %>
					<%= render :partial => "layouts/user_info" %>
				<% else %>
					<%= link_to_function "login", "hyd.display_login_form()" %>
					or
					<%= link_to "sign up", new_user_path %>
					<%= render :partial => "layouts/login_form" %>
				<% end %>
			</div>
		</div>
		<div id="content">
			<div id="flash">
				<%= render "layouts/messages" %>
			</div>
			<%= yield %>
		</div>
		<div id="footer">
			Copyright 2011. All rights reserved.
			<span id="navigation"><%= link_to "About", "/home/about" %></span>
		</div>
	</div>
</body>
</html>